FROM node:16.13.1 as build

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json /usr/src/app

RUN npm install

COPY . /usr/src/app

EXPOSE 3000

CMD [ "npm", "start" ]
# RUN npm run build

# FROM nginx:alpine
# COPY --from=build /usr/src/app/build /usr/share/nginx/html
# COPY /proxy/nginx.conf /etc/nginx/nginx.conf

# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
