"""empty message

Revision ID: 4d9ff862ad16
Revises: a53fd4640691
Create Date: 2021-11-29 14:15:09.628363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9ff862ad16'
down_revision = 'a53fd4640691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access_token', sa.String(length=1024), nullable=True))
    op.add_column('user', sa.Column('refresh_token', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refresh_token')
    op.drop_column('user', 'access_token')
    # ### end Alembic commands ###
