"""empty message

Revision ID: 60831c1de43c
Revises: be83106b7fa2
Create Date: 2021-11-24 20:09:13.568803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60831c1de43c'
down_revision = 'be83106b7fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('views', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'views')
    # ### end Alembic commands ###
