"""empty message

Revision ID: 92a53360d6d8
Revises: 
Create Date: 2021-12-02 15:51:56.348865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92a53360d6d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access_token', sa.String(length=1024), nullable=True))
    op.add_column('user', sa.Column('refresh_token', sa.String(length=1024), nullable=True))
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.drop_column('user', 'refresh_token')
    op.drop_column('user', 'access_token')
    # ### end Alembic commands ###
