"""empty message

Revision ID: a53fd4640691
Revises: dbb023cbfcd9
Create Date: 2021-11-24 20:12:24.829394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a53fd4640691'
down_revision = 'dbb023cbfcd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('likes', sa.Integer(), nullable=False))
    op.drop_column('recipe', 'like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('like', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('recipe', 'likes')
    # ### end Alembic commands ###
