"""empty message

Revision ID: be83106b7fa2
Revises: 2c1952d55a01
Create Date: 2021-11-24 20:06:45.186608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be83106b7fa2'
down_revision = '2c1952d55a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'like')
    op.drop_column('recipe', 'views')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('views', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('recipe', sa.Column('like', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
