"""empty message

Revision ID: dbb023cbfcd9
Revises: 60831c1de43c
Create Date: 2021-11-24 20:10:51.818300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb023cbfcd9'
down_revision = '60831c1de43c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('like', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'like')
    # ### end Alembic commands ###
